# Generated by Django 4.0.4 on 2022-05-23 13:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Post',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('title', models.CharField(max_length=30, verbose_name='Title')),
        ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug')),
        ('content', models.TextField(verbose_name='Content')),
        ('published', models.BooleanField(default=False, verbose_name='Published')),
        ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
      ],
    ),
  ]
