# Generated by Django 4.0.4 on 2022-05-19 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('users', '0001_initial'),
  ]

  operations = [
    migrations.AlterField(
      model_name='user',
      name='phone_number',
      field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^(0|90)(\\d{10})$')], verbose_name='Phone Number'),
    ),
    migrations.AlterField(
      model_name='user',
      name='whatsapp',
      field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^(0|90)(\\d{10})$')], verbose_name='Whatsapp Number'),
    ),
  ]
