# Generated by Django 4.0.4 on 2022-07-05 13:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Ticket',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('ticket', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(32)], verbose_name='Ticket')),
        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL, verbose_name='User')),
      ],
    ),
  ]
