# Generated by Django 4.0.6 on 2022-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='okundumu?'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='ne zaman gonderildi?'),
        ),
    ]
