# Generated by Django 4.0.6 on 2022-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='başlık')),
                ('content', models.TextField(verbose_name='içerik')),
            ],
            options={
                'verbose_name': 'sıkça sorulan soru',
                'verbose_name_plural': 'sıkça sorulan sorular',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='medya adı')),
                ('link', models.TextField(verbose_name='medya linki')),
                ('icon_class', models.CharField(max_length=255, verbose_name='font-awesome class')),
            ],
            options={
                'verbose_name': 'medya hesabı',
                'verbose_name_plural': 'medya hesapları',
            },
        ),
    ]
