# Generated by Django 4.0.4 on 2022-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_alter_user_free_consultacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_area',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='City Area'),
        ),
    ]
