# Generated by Django 4.0.4 on 2022-06-26 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_area_user_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='free_consultacy',
            new_name='consultacy_free',
        ),
        migrations.AddField(
            model_name='user',
            name='consultacy_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Consultacy Price? (₺)'),
        ),
    ]
