# Generated by Django 4.0.4 on 2022-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_free_consultacy_user_consultacy_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Test', verbose_name='Bio (Markdown)'),
            preserve_default=False,
        ),
    ]
