# Generated by Django 4.0.4 on 2022-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length='2000', verbose_name='Bio (Markdown)'),
        ),
    ]
