# Generated by Django 4.0.4 on 2022-07-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='consultacy_free',
            new_name='free_consultacy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consultacy_price',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
