# Generated by Django 4.0.4 on 2022-07-07 21:58

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_consultacy_free_user_free_consultacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='areas',
            field=models.ManyToManyField(to='users.area'),
        ),
    ]
