# Generated by Django 4.0.4 on 2022-07-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_area_user_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='areas',
            field=models.ManyToManyField(related_name='areas', to='users.area'),
        ),
    ]
