# Generated by Django 4.0.4 on 2022-07-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price_consultacy',
            field=models.IntegerField(default=0, verbose_name='Consultacy Price?'),
        ),
    ]
