# Generated by Django 4.0.4 on 2022-07-08 00:55

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('users', '0012_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='areas',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
