# Generated by Django 4.0.4 on 2022-07-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_areas_user_tags_delete_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatars/default.png', upload_to='users/avatars', verbose_name='Avatar'),
        ),
    ]
