# Generated by Django 4.0.4 on 2022-05-23 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Conversation',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('users', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
      ],
    ),
    migrations.CreateModel(
      name='Message',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('text', models.CharField(max_length=500, verbose_name='Text')),
        ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.conversation', verbose_name='Conversation')),
        ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
      ],
    ),
  ]
