# Generated by Django 4.0.6 on 2022-08-27 12:40

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='başlık')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('published', models.BooleanField(default=False, verbose_name='yayınlama tarihi')),
                ('image', models.ImageField(default='posts/images/default.jpg', upload_to='posts/images', verbose_name='görsel')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='yazı tarihi')),
                ('tags', models.ManyToManyField(to='users.area', verbose_name='ilgili alanlar')),
            ],
            options={
                'verbose_name': 'haber',
                'verbose_name_plural': 'haberler',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='tarih')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'yorum',
                'verbose_name_plural': 'yorumlar',
            },
        ),
    ]
