# Generated by Django 4.0.4 on 2022-05-23 14:11

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Post',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('title', models.CharField(max_length=30, verbose_name='Title')),
        ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug')),
        ('content', models.TextField(verbose_name='Content')),
        ('published', models.BooleanField(default=False, verbose_name='Published')),
        ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
      ],
    ),
    migrations.CreateModel(
      name='Comment',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('content', models.TextField(verbose_name='Content')),
        ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post')),
        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment')),
      ],
    ),
  ]
